# Generated by Django 2.0.1 on 2018-04-02 09:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0002_auto_20180401_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user_id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='user_id',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
